export const rowData = ['Vegetables', 'Fruits', 'Dairy', 'Meat'];

export const staticData = [
  {
    id: 1,
    productImg: require('../assets/images/item1.png'),
    productName: 'Green Seedless Grapes',
    productPrice: '2.47',
    perkg: '$10.29/KG',
    minWeight: 'min 500g',
    soldBy: 'Harris Farm Markets',
    stock: 'In Stock',
    categories: 'Fruits',
    qty: 0,
    desc: 'Aliquam lorem ante, dapibus in, viverra quis, eugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
  },
  {
    id: 2,
    productImg: require('../assets/images/item2.png'),
    productName: 'Lemons',
    productPrice: '2.47',
    perkg: '$10.29/KG',
    minWeight: 'min 500g',
    soldBy: 'Harris Farm Markets',
    stock: 'In Stock',
    categories: 'Vegetables',
    qty: 0,
    desc: 'Aliquam lorem ante, dapibus in, viverra quis, eugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
  },
  {
    id: 3,
    productImg: require('../assets/images/item3.png'),
    productName: 'oranges',
    productPrice: '2.47',
    perkg: '$10.29/KG',
    minWeight: 'min 500g',
    soldBy: 'YCC Paultry',
    stock: 'In Stock',
    categories: 'Dairy',
    qty: 0,
    desc: 'Aliquam lorem ante, dapibus in, viverra quis, eugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
  },
  {
    id: 4,
    productImg: require('../assets/images/item4.png'),
    productName: 'Pineapples',
    productPrice: '2.47',
    perkg: '$10.29/KG',
    minWeight: 'min 500g',
    soldBy: 'Harris Farm Markets',
    stock: 'In Stock',
    categories: 'Fruits',
    qty: 0,
    desc: 'Aliquam lorem ante, dapibus in, viverra quis, eugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
  },
  {
    id: 5,
    productImg: require('../assets/images/item1.png'),
    productName: 'Green Seedless Grapes',
    productPrice: '2.47',
    perkg: '$10.29/KG',
    minWeight: 'min 500g',
    soldBy: 'Harris Farm Markets',
    stock: 'In Stock',
    categories: 'Fruits',
    qty: 0,
    desc: 'Aliquam lorem ante, dapibus in, viverra quis, eugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
  },
  {
    id: 6,
    productImg: require('../assets/images/item2.png'),
    productName: 'Lemon',
    productPrice: '2.47',
    perkg: '$10.29/KG',
    minWeight: 'min 500g',
    soldBy: 'Harris Farm Markets',
    stock: 'In Stock',
    categories: 'Vegetables',
    qty: 0,
    desc: 'Aliquam lorem ante, dapibus in, viverra quis, eugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
  },
  {
    id: 7,
    prodctImg: require('../assets/images/item3.png'),
    productName: 'Oranges',
    productPrice: '2.47',
    perkg: '$10.29/KG',
    minWeight: 'min 500g',
    soldBy: 'Harris Farm Markets',
    stock: 'In Stock',
    categories: 'Dairy',
    qty: 0,
    desc: 'Aliquam lorem ante, dapibus in, viverra quis, eugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
  },
  {
    id: 8,
    productImg: require('../assets/images/item4.png'),
    productName: 'Pineapples',
    productPrice: '2.47',
    perkg: '$10.29/KG',
    minWeight: 'min 500g',
    soldBy: 'Harris Farm Markets',
    stock: 'In Stock',
    categories: 'Vegetables',
    qty: 0,
    desc: 'Aliquam lorem ante, dapibus in, viverra quis, eugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
  },
];
